### ISSUE TITLE
使用 css module 改造现有样式，同时提供静态的 className 供样式覆盖使用

### ISSUE THREAD

**Issue by fengkx** [banyudu/kedao#13]
在npm 发包直接发布源码的话，css moudle 的话应该需要额外的webpack配置？ 虽然cra，next 都支持`moudle.css`的写法但是我觉得不应该在组件里面使用。 用一些不需要编译方案的css in js是不是更好例如 `@emotion/css`

**Comment by fengkx** [comment]
如果用css moudle这个改动是break change， 流水线发包是否支持指定版本号？

**Comment by banyudu** [comment]
> 如果用css moudle这个改动是break change， 流水线发包是否支持指定版本号？

合并 master 之前手动更新版本号应该就行了
