### ISSUE TITLE
Link 组件的输入框无法使用，点击后弹出框会自动消失

### ISSUE THREAD

**Issue by banyudu** [banyudu/kedao#19]
![](https://user-images.githubusercontent.com/2416493/175849077-83340cde-796d-413c-b88a-b0bdaafbd6f4.png)

**Comment by fengkx** [comment]
0.1.19 中无法复现，能正常使用，是不是已经修了？

**Comment by banyudu** [comment]
还没有修复。

复现方式：先选中一段文本，再点击工作栏 Link 按钮，弹出对话框之后，点击输入框。此时输入框会自动消失。
再次重试时正常。

目前分析到的原因在于：EditorState 发生了变化（原因尚不清楚，有可能是选中状态或者鼠标锚点位置变化导致），触发了 Toolbar 重新渲染，继而导致 Input 组件销毁，弹出框消失。
