### ISSUE TITLE
自定义组件无法传递 disabled 属性

### ISSUE THREAD

**Issue by slobber** [banyudu/kedao#43]
使用 HtmlButton 后，内部控件会被 disabled，但自定义组件不支持。
<img width="729" alt="image" src="https://user-images.githubusercontent.com/1853799/202616636-a3ba5e49-5d90-471a-8c66-331125119a7f.png">

**Comment by banyudu** [comment]
已发布 [v1.1.1](https://www.npmjs.com/package/kedao/v/1.1.1)
